# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ed976d955112273977b3b5b75047c08b65a82a8ebed3602846368b54bbb27b6382b7b78d7a903ffd1fb6d26387c4fa397b18381dca13570ac3472b5133f563
  vkontakte_app_id: 5009828
  vkontakte_app_secret: iP04CiisMOuWWHJYqNxS
  facebook_app_id: 1595156724079051
  facebook_app_secret: 91ce6534e4c0020d8f6e107b8a996d57
  twitter_app_id:  HDuXBXPaLS2X3rGAvIiKy0SLb
  twitter_app_secret: NzyPNiBhy1PwokiAS7fEwKKO4uwpvljsigaYm8E1o0Q0iXkuz0
test:
  secret_key_base: dc1cd2e34912805af7aa7434a21836f738cd87c49b823cd802f40c8e95e9e99ec61703d7e1fbe0c69ad5257c371f4863834fbc2c097861b21eb66af3b869ab73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  vkontakte_app_id: <%= ENV["VKONTAKTE_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VKONTAKTE_APP_SECRET"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id:  <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
